version: '3.8'

services:
  postgres:
    container_name: app_login-auth-api
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=login
